nodes:
- name: pc
  ip: 127.0.0.1
  port: 8080
  priority: 100
  last_updated: 2025-02-04 19:19:18 UTC
- name: phone
  ip: 100.11.111.111
  port: 8081
  priority: 20
  last_updated: 2025-01-09 16:45:00 UTC
config_metadata:
  name: pc
  last_updated: 2025-01-11 10:00:00 UTC
execution:
  instructions: ./test-script.sh
  last_updated: 2025-01-11 10:00:00 UTC
